# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VistaHomeDirettore.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VistaHomeDirettore(object):
    def setupUi(self, VistaHomeDirettore):
        VistaHomeDirettore.setObjectName("VistaHomeDirettore")
        VistaHomeDirettore.resize(400, 421)
        self.pushButton_1 = QtWidgets.QPushButton(VistaHomeDirettore)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 0, 200, 140))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_4 = QtWidgets.QPushButton(VistaHomeDirettore)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 140, 200, 140))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(VistaHomeDirettore)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 0, 200, 140))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(VistaHomeDirettore)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 140, 200, 140))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(VistaHomeDirettore)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 280, 200, 140))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(VistaHomeDirettore)
        QtCore.QMetaObject.connectSlotsByName(VistaHomeDirettore)

    def retranslateUi(self, VistaHomeDirettore):
        _translate = QtCore.QCoreApplication.translate
        VistaHomeDirettore.setWindowTitle(_translate("VistaHomeDirettore", "Form"))
        self.pushButton_1.setText(_translate("VistaHomeDirettore", "Utente"))
        self.pushButton_4.setText(_translate("VistaHomeDirettore", "Informazioni e contatti"))
        self.pushButton_3.setText(_translate("VistaHomeDirettore", "Prenotazioni"))
        self.pushButton_2.setText(_translate("VistaHomeDirettore", "Beni"))
        self.pushButton_5.setText(_translate("VistaHomeDirettore", "Elimina dipendenti"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VistaHomeDirettore = QtWidgets.QWidget()
    ui = Ui_VistaHomeDirettore()
    ui.setupUi(VistaHomeDirettore)
    VistaHomeDirettore.show()
    sys.exit(app.exec_())
