# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VistaAggiungiPrenotazione.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(322, 164)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 20, 321, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Label_nome = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_nome.setFont(font)
        self.Label_nome.setObjectName("Label_nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_nome)
        self.nomeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nomeLineEdit.setObjectName("nomeLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nomeLineEdit)
        self.Label_cognome = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_cognome.setFont(font)
        self.Label_cognome.setObjectName("Label_cognome")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_cognome)
        self.cognomeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cognomeLineEdit.setObjectName("cognomeLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cognomeLineEdit)
        self.Label_attivita = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_attivita.setFont(font)
        self.Label_attivita.setObjectName("Label_attivita")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_attivita)
        self.attivitaComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.attivitaComboBox.setObjectName("attivitaComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.attivitaComboBox)
        self.Label_date = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_date.setFont(font)
        self.Label_date.setObjectName("Label_date")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_date)
        self.datePrenotabiliComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.datePrenotabiliComboBox.setObjectName("datePrenotabiliComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.datePrenotabiliComboBox)
        self.pushButton_prenota = QtWidgets.QPushButton(Form)
        self.pushButton_prenota.setGeometry(QtCore.QRect(110, 130, 101, 23))
        self.pushButton_prenota.setObjectName("pushButton_prenota")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "InserisciPrenotazione"))
        self.Label_nome.setText(_translate("Form", "Nome:"))
        self.Label_cognome.setText(_translate("Form", "Cognome:"))
        self.Label_attivita.setText(_translate("Form", "Attività:"))
        self.Label_date.setText(_translate("Form", "Date prenotabili:"))
        self.pushButton_prenota.setText(_translate("Form", "Prenota attività"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
