from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VistaUtente(object):
    def setupUi(self, VistaUtente):
        VistaUtente.setObjectName("VistaUtente")
        VistaUtente.resize(300, 200)
        self.label_1 = QtWidgets.QLabel(VistaUtente)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 82, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(VistaUtente)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 86, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(VistaUtente)
        self.label_3.setGeometry(QtCore.QRect(90, 20, 82, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(VistaUtente)
        self.label_4.setGeometry(QtCore.QRect(120, 60, 82, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_1 = QtWidgets.QPushButton(VistaUtente)
        self.pushButton_1.setGeometry(QtCore.QRect(30, 140, 91, 41))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(VistaUtente)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 140, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(VistaUtente)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 86, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(VistaUtente)
        self.label_6.setGeometry(QtCore.QRect(120, 100, 82, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(VistaUtente)
        QtCore.QMetaObject.connectSlotsByName(VistaUtente)

    def retranslateUi(self, VistaUtente):
        _translate = QtCore.QCoreApplication.translate
        VistaUtente.setWindowTitle(_translate("VistaUtente", "Gestione utente"))
        self.label_1.setText(_translate("VistaUtente", "Email:"))
        self.label_2.setText(_translate("VistaUtente", "Password:"))
        self.label_3.setText(_translate("VistaUtente", "TextLabel"))
        self.label_4.setText(_translate("VistaUtente", "TextLabel"))
        self.pushButton_1.setText(_translate("VistaUtente", "Aggiorna"))
        self.pushButton_2.setText(_translate("VistaUtente", "Elimina"))
        self.label_5.setText(_translate("VistaUtente", "Password:"))
        self.label_6.setText(_translate("VistaUtente", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VistaUtente = QtWidgets.QWidget()
    ui = Ui_VistaUtente()
    ui.setupUi(VistaUtente)
    VistaUtente.show()
    sys.exit(app.exec_())
